version: '3'

services:

 haproxy:
    build: haproxy
    ports:
      - "8090:80"
    networks:
      - mynet

 server1:
    build: app
    networks:
      - mynet

 server2:
    build: app
    networks:
      - mynet

networks:

  mynet:
    driver: bridge
